/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_BannerAdsJni */

#ifndef _Included_com_common_android_ads_jni_BannerAdsJni
#define _Included_com_common_android_ads_jni_BannerAdsJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeOnBannerLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeOnBannerLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeOnBannerFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeOnBannerFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeOnBannerClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeOnBannerClicked
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeOnBannerCollapsed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeOnBannerCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_BannerAdsJni
 * Method:    nativeOnBannerExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_BannerAdsJni_nativeOnBannerExpanded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
