/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_InterstitialAdsJni */

#ifndef _Included_com_common_android_ads_jni_InterstitialAdsJni
#define _Included_com_common_android_ads_jni_InterstitialAdsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeOnInterstitialLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeOnInterstitialLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeOnInterstitialFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeOnInterstitialFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeOnInterstitiaExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeOnInterstitialExpanded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeOnInterstitiaCollapsed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeOnInterstitialCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_InterstitialAdsJni
 * Method:    nativeOnInterstitialClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_InterstitialAdsJni_nativeOnInterstitialClicked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
