/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_CrosspromoAdsJni */

#ifndef _Included_com_common_android_ads_jni_CrosspromoAdsJni
#define _Included_com_common_android_ads_jni_CrosspromoAdsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeOnCrosspromoLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeOnCrosspromoLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeOnCrosspromoFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeOnCrosspromoFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeOnCrosspromoExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeOnCrosspromoExpanded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeOnCrosspromoCollapsed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeOnCrosspromoCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_CrosspromoAdsJni
 * Method:    nativeOnCrosspromoClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_CrosspromoAdsJni_nativeOnCrosspromoClicked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
