/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_RectAdsJni */

#ifndef _Included_com_common_android_ads_jni_RectAdsJni
#define _Included_com_common_android_ads_jni_RectAdsJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeInit
  (JNIEnv *, jobject);
/*
 * Class:     com_common_android_ads_jni_RectAdsJni
 * Method:    nativeOnRectLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeOnRectLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_RectAdsJni
 * Method:    nativeOnRectFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeOnRectFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_RectAdsJni
 * Method:    nativeOnRectClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeOnRectClicked
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_RectAdsJni
 * Method:    nativeOnRectCollapsed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeOnRectCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_RectAdsJni
 * Method:    nativeOnRectExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RectAdsJni_nativeOnRectExpanded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
