/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_NativeBannerAdsJni */

#ifndef _Included_com_common_android_ads_jni_NativeBannerAdsJni
#define _Included_com_common_android_ads_jni_NativeBannerAdsJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeOnNativeAdsLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeOnNativeAdsLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeOnNativeAdsFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeOnNativeAdsFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeOnNativeAdsClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeOnNativeAdsClicked
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeOnNativeAdsCollapsed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeOnNativeAdsCollapsed
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_NativeBannerAdsJni
 * Method:    nativeOnNativeAdsExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_NativeBannerAdsJni_nativeOnNativeAdsExpanded
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
