/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_ads_jni_RewardedAdsJni */

#ifndef _Included_com_common_android_ads_jni_RewardedAdsJni
#define _Included_com_common_android_ads_jni_RewardedAdsJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeInit
  (JNIEnv *, jobject);
/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeOnRewardedLoaded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewardedLoaded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeOnRewardedFailed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewardedFailed
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeOnRewardedExpanded
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewardedExpanded
  (JNIEnv *, jobject);

/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeOnRewardedCollapsed
 * Signature: (Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewardedCollapsed
  (JNIEnv *, jobject);


JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewarded
  (JNIEnv *, jobject, jstring, jint, jboolean);
/*
 * Class:     com_common_android_ads_jni_RewardedAdsJni
 * Method:    nativeOnRewardedClicked
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_ads_jni_RewardedAdsJni_nativeOnRewardedClicked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
