/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_helper_MICAudioManager */

#ifndef _Included_com_helper_MICAudioManager
#define _Included_com_helper_MICAudioManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_helper_MICAudioManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_helper_MICAudioManager_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
