/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_common_android_AnalyticsCenterJni_AnalyticsCenterJni */

#ifndef _Included_com_common_android_analyticscenter_AnalyticsCenterJni
#define _Included_com_common_android_analyticscenter_AnalyticsCenterJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_common_android_AnalyticsCenterJni_AnalyticsCenterJni
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_common_android_analyticscenter_AnalyticsCenterJni_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
